# Generated by Django 5.1.2 on 2024-11-02 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dailytask_salat_status_dailytask_asr_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
