# Generated by Django 5.1.2 on 2024-11-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_constitution_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Other', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
